language: node_js

node_js:
  - 10

addons:
  apt:
    update: true
    packages:
      - zsh

cache:
  npm: false

git:
  depth: false

env:
  ZSH=${HOME}/.oh-my-zsh

before_install:
  - zsh --version

before_script:
  - npm test

script:
  - npm run build

deploy:
  - provider: pages
    local_dir: public
    skip_cleanup: true
    keep_history: true
    github_token: ${GIT_REPO_TOKEN}
    target_branch: gh-pages
    on:
      branch: master

  - provider: npm
    skip_cleanup: true
    email: "${NPM_USER_EMAIL}"
    api_key: "${NPM_AUTH_TOKEN}"
    on:
      branch: master
      tags: true

notifications:
  email: true
  on_success: always
  on_failure: always
