# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: release

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        # https://github.com/actions/checkout
        uses: actions/checkout@v2
        with:
          # Number of commits to fetch. 0 indicates all history.
          # all history for changelog
          fetch-depth: 0

      - name: Prepare for building
        uses: ./.github/actions/prepare

      - name: Build
        run: |
          npm run build

      - name: Unit test
        # test for build file
        run: |
          npm test

      - name: Publish to npm
        # https://docs.github.com/en/actions/guides/publishing-nodejs-packages#publishing-packages-to-the-npm-registry
        id: publish-to-npm
        env:
          # need set in GitHub repo - settings - secrets
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm publish
