# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: renovate

on:
  workflow_dispatch:
    branches:
      - master
  schedule:
    # https://crontab.guru
    - cron: '0 * * * *'
      branches:
        - master

jobs:
  renovate:
    runs-on: ubuntu-latest
    env:
      # https://github.com/chalk/supports-color/blob/main/index.js#L21
      # https://github.com/chalk/supports-color/blob/main/index.js#L54
      FORCE_COLOR: true

    steps:
      - name: Checkout
        # https://github.com/actions/checkout
        uses: actions/checkout@v2

      - name: Renovate
        # https://github.com/renovatebot/github-action
        uses: renovatebot/github-action@v25.18.5
        with:
          configurationFile: .github/renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
